### ISSUE TITLE
Implement user authentication and authorization

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Resource-Sharing-App#13]
Include pages for user registration, login, and password reset. These pages should have input fields for email, password, and appropriate error handling messages.

**Comment by GaganChaudhary6378** [comment]
Hi, i want to work on this issue. So can i use nextauth for this?

**Comment by akshit-g** [comment]
> Hi, i want to work on this issue. So can i use nextauth for this?
Assigned!
The tech stack for the project is Django. Just ensure proper integration between the django template and the Next.js + nextauth

**Comment by rohin079** [comment]
I would like to work on this issue under Osoc'23

**Comment by akshit-g** [comment]
> I would like to work on this issue under Osoc'23

Assigned!
