### ISSUE TITLE
Implement frontend for error pages

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Resource-Sharing-App#14]
Create error pages for common HTTP error codes like 404 (Page Not Found) or 500 (Internal Server Error). These pages should provide a clear message and suggest actions for users to take.

**Comment by akshit-g** [comment]
> 

Assigned

**Comment by shradiphylleia** [comment]
would like to work on this.

**Comment by akshit-g** [comment]
> would like to work on this.

Assigned

**Comment by akshit-g** [comment]
Completed by @shradiphylleia
