### ISSUE TITLE
Implement frontend for user profile section

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Resource-Sharing-App#17]
Allow users to view and edit their profiles. Display information such as the user's name, profile picture, bio, uploaded resources, and any other relevant details. Include an option to update profile information or change the profile picture.

**Comment by Anabot12** [comment]
i want to work on this issue!

**Comment by akshit-g** [comment]
> i want to work on this issue!
> 

Assigned

**Comment by shradiphylleia** [comment]
please assign this issue to me.

**Comment by akshit-g** [comment]
Completed by @shradiphylleia
