### ISSUE TITLE
Implement frontend for navbar and footer

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Resource-Sharing-App#3]

**Comment by vasanthanb** [comment]
I can work on this issue

**Comment by akshit-g** [comment]
> I can work on this issue, assign this to me under osoc'23

Assigned!

**Comment by vasanthanb** [comment]
@akshit-g I added the basic navbar and footer. I don't know much css right now , so I need someone else to work on the styling part.

**Comment by akshit-g** [comment]
> @akshit-g I added the basic navbar and footer. I don't know much css right now , so I need someone else to work on the styling part.

Sorry, but for the PR to be accepted you need to complete 90-100% of the requirements. It's a part of OSoC rules.

**Comment by avnigoyal25** [comment]
i can work on this issue

**Comment by akshit-g** [comment]
> i can work on this issue

Assigned

**Comment by akshit-g** [comment]
Completed by @avnigoyal25
