### ISSUE TITLE
Implement frontend for the homepage

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Resource-Sharing-App#7]
Display a list of resources with relevant information such as the title, description, tags, upload date, and user who uploaded it. Users can browse through the list to find resources they are interested in.

**Comment by Anabot12** [comment]
i want to work on this issue

**Comment by akshit-g** [comment]
> i want to work on this issue

Assigned!

**Comment by avnigoyal25** [comment]
i want to work on this issue

**Comment by akshit-g** [comment]
Completed by @avnigoyal25
