### ISSUE TITLE
Implement frontend for the resource upload form

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Resource-Sharing-App#8]
Provide a form where users can upload educational resources. Include fields for the resource title, description, file upload, tags, and any other relevant information.

**Comment by GaganChaudhary6378** [comment]
Hi , I want to work on this issue. For this I can use multer for file uploading.

**Comment by akshit-g** [comment]
> Hi , I want to work on this issue. For this I can use multer for file uploading.

Assigned!

**Comment by mswat5** [comment]
hey @akshit-g can i work on this?

**Comment by akshit-g** [comment]
> hey @akshit-g can i work on this?

Sure. Assigned!

**Comment by akshit-g** [comment]
Completed by @avnigoyal25
